slogan: "wubba lubba dub dub."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  - title: hexo-theme-bithack
    url: https://github.com/Ares-X/hexo-theme-freemind.bithack
    intro: ""
    icon: false

  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-70812759-1
baidu_tongji:
  enable: true
  siteid: cb5448498d7169c668b07c2b255d62c1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
#valine comment (change to yours)
valine: 
  enable: true
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: "提交评论时留下邮箱收到回复后将自动通知"
  visitor: true
  avatar: 'monsterid'
  requiredFields: ['nick','mail']


auto_excerpt:
    enable: true
    lines: 50
